### ISSUE TITLE
Failed to compile main.dart

### ISSUE THREAD

**Issue by micrcx** [jimbeveridge/bouncing_circles#2]
I tried to create a new flutter project and include to this project main.dart, but I ran into two compilation problems:
1) The Point class in the Circle class is not defined: Undefined class 'Point'
2) A problem with the AnimationController class, a prompt appears: The parameter 'vsync' is required.
How to adapt your sample to the latest changes in the flutter?

**Comment by micrcx** [comment]
Thanks for help. Just one thing:  line "willChange: true," in the 'build'
function should be deleted, otherwise appears compilation error.

 @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text('Bouncing Circles')),
        body: new Builder(
            builder: (context) => new GestureDetector(
                onTapDown: (TapDownDetails details) =>
                    _tapped(context, details),
                child: new Container(
                    decoration:
                    new BoxDecoration(
                    color: const Color(0xFFC9B0BB)),
                    child: new CustomPaint(
                    //    willChange: true, <=== This line should be
deleted, otherwise appears compilation error.
                        child: new Container(),
                        foregroundPainter: new CirclePainter(circles))))),
        floatingActionButton: new FloatingActionButton(
            onPressed: _clearCircles,
            tooltip: 'Clear',
            child: new Icon(Icons.clear)));
  }
}

Regards,
Michael K

**Comment by jimbeveridge** [comment]
Thanks for the feedback Michael. This flag was added to Flutter two weeks ago, so I think you just need to update Flutter. Here's the commit:
https://github.com/flutter/flutter/commit/838bd63182f0bb0dbd2cb293821e91601300fc52

**Comment by micrcx** [comment]
Thank you.
The update came just today and your add-on is now relevant. By the way, how
difficult is it to modify your application under multi touch? I've found
that flutter has the MultiTapGestureRecognizer class. I just don't
understand how in this application it can be used. And can be used it at
all?
Regards,
Michael K.
